# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=120)),
                ('requests', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(default=0)),
                ('person', models.CharField(max_length=120)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('friend', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField()),
                ('person', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=120)),
                ('lastlogin', models.DateTimeField(auto_now=True)),
                ('ipaddress', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('First_name', models.CharField(default='', max_length=120)),
                ('Last_name', models.CharField(default='', max_length=120)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('coverpic', models.ImageField(blank=True, default='', null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=120)),
                ('post', models.TextField(blank=True, default='', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
