# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
