# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_auto_20170814_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commnet',
            field=models.IntegerField(default=0),
        ),
    ]
