# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_post_commnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commnet',
            new_name='comment',
        ),
    ]
