# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0006_auto_20170816_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='person_id',
            field=models.IntegerField(default=0),
        ),
    ]
