node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        
        docker.withRegistry('https://hub.docker.com/r/shobhit2222/docker_jenkins/', 'docker-hub-credentials') {
            /* app.push("${env.BUILD_NUMBER}") 
            app.push("latest") */
            app = docker.build("r/shobhit2222/docker_jenkins","-f django2/clone/Dockerfile .") 
            app.push()
        }

      
}

}

